package ticket.com.tickettoridegames.utility;

public enum TYPE {
    START, ALLCHAT, NEWCHAT, STATSUPDATE, HISTORYUPDATE, BANKUPDATE, NEWROUTE, NEWTRAINCARD, NEWTEMPDECK, DESTINATIONUPDATE, DISCARDDESTINATION;
}
